language: c++
compiler: gcc
install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get -qq install g++-4.8
    - export CXX="g++-4.8"
#    - sudo apt-get -qq install libboost-dev
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/b/boost1.55/libboost-test1.55-dev_1.55.0-1_amd64.deb
    - sudo dpkg -i libboost-test1.55-dev_1.55.0-1_amd64.deb
script: "cmake . && make && make test"
