language: c++
compiler: gcc
install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.8
    - sudo apt-get -qq install libboost1.55-all-dev
script: "cmake . && make && make test"