language: c++
compiler: gcc
install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get -qq install g++-4.8
    - export CXX="g++-4.8"
    - sudo apt-get -qq install libboost-dev
script: "cmake . && make && make test"
